title: Data Assignments
description: An overview of the Data Assigments of Group 5
theme: just-the-docs

url: https://iepebouw.github.io/data1/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
favicon_ico: "/assets/favicon.ico"
